const Constants = {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_MOVIES: 'FETCH_MOVIES',
    FETCH_MOVIE: 'FETCH_MOVIE',
    SET_MOVIE: 'SET_MOVIE',
    REVIEW_SAVED: 'REVIEW_SAVED',
    FETCH_MOVIE_BEGIN: 'FETCH_MOVIE_BEGIN',
    FETCH_MOVIE_ERROR: 'FETCH_MOVIE_ERROR',
    SEARCH_MOVIES_BEGIN: 'SEARCH_MOVIES_BEGIN',
    SEARCH_MOVIES_SUCCESS: 'SEARCH_MOVIES_SUCCESS',
    SEARCH_MOVIES_ERROR: 'SEARCH_MOVIES_ERROR'
}

export default Constants;